name: Linux

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  pull_request:
  # Enable manual run
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup-phpunit-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: gen
        uses: galette/.github/actions/matrix-generator@main
        with:
          all-jobs: ${{ github.event_name != 'pull_request' && github.repository == 'galette/galette-paypal' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')) }}

  setup-lint-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: gen
        uses: galette/.github/actions/matrix-generator@main
        with:
          target: lint
          all-jobs: ${{ github.event_name != 'pull_request' && github.repository == 'galette/galette-paypal' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')) }}

  lint:
    runs-on: ubuntu-latest
    needs: setup-lint-matrix
    name: "Lint on PHP ${{ matrix.php-version }}"

    strategy:
      matrix: ${{ fromJSON(needs.setup-lint-matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: ${{ matrix.coverage }}

      - name: Checkout Galette core
        uses: actions/checkout@v6
        with:
          repository: galette/galette
          path: galette-core
          fetch-depth: 1
          ref: develop

      - name: Checkout plugin
        uses: actions/checkout@v6
        with:
          path: galette-core/galette/plugins/plugin-paypal

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          cd galette-core
          composer install --ignore-platform-reqs

      - name: CS
        run: |
          cd galette-core/galette/plugins/plugin-paypal
          ../../vendor/bin/phpcs lib/ ./*.php

      - name: CS Fixer
        if: matrix.php-is-min
        run: |
          cd galette-core/galette/plugins/plugin-paypal
          ../../vendor/bin/php-cs-fixer check --show-progress=dots --verbose --diff

      - name: Twig CS
        run: |
          cd galette-core/galette/plugins/plugin-paypal
          ../../vendor/bin/twigcs templates/default --severity error --display blocking

      - name: PHPStan checks
        run: |
          cd galette-core/galette/plugins/plugin-paypal
          ../../vendor/bin/phpstan analyze --ansi --memory-limit=2G --no-interaction --no-progress

      - name: Headers checks
        run: |
          cd galette-core/galette/plugins/plugin-paypal
          ../../vendor/bin/docheader --docheader=../../../.docheader check lib ./*.php

  unit-tests:
    runs-on: ubuntu-latest
    needs: setup-phpunit-matrix

    strategy:
      matrix: ${{ fromJSON(needs.setup-phpunit-matrix.outputs.matrix) }}
      fail-fast: false

    env:
      DB: ${{ matrix.db-image }}

    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: ${{ matrix.db-image }}
        # Provide env variables for both mysql and pgsql
        env:
          POSTGRES_USER: galette_tests
          POSTGRES_PASSWORD: g@l3tte
          POSTGRES_DB: galette_tests
          MYSQL_USER: galette_tests
          MYSQL_PASSWORD: g@l3tte
          MYSQL_ROOT_PASSWORD: g@l3tte
          MYSQL_DATABASE: galette_tests
        # Open network ports for both mysql and pgsql
        ports:
          - 3306:3306
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd="bash -c 'if [[ -n $(command -v pg_isready) ]]; then pg_isready; else if [[ -n $(command -v mysqladmin) ]]; then mysqladmin ping; else mariadb-admin ping; fi fi'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    name: PHP ${{ matrix.php-version }} ${{ matrix.db-image }} ${{ (matrix.always == false && (github.event_name == 'pull_request' || github.repository != 'galette/plugin-paypal' || !(github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')))) && ' (skipped)' || matrix.coverage == 'xdebug' && ' (with coverage)' || ''}}

    steps:
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer, pecl
          coverage: ${{ matrix.coverage }}
          extensions: apcu
          ini-values: apc.enable_cli=1

      - name: "Show versions"
        run: |
          php --version
          composer --version
          echo "node $(node --version)"
          echo "npm $(npm --version)"
          docker exec ${{ job.services.db.id }} bash -c "if [[ -n \$(command -v psql) ]]; then psql --version; else if [[ -n \$(command -v mysql) ]]; then mysql --version; else mariadb --version; fi fi"

      - name: Build Galette
        uses: galette/.github/actions/build-galette@main
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout plugin
        uses: actions/checkout@v6
        with:
          path: galette-core/galette/plugins/plugin-paypal

      - name: Init for PostgreSQL
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          cd galette-core
          bin/console galette:install -v --dbtype=pgsql --dbhost=localhost --dbname=galette_tests --dbuser=galette_tests --dbpass=g@l3tte --admin=admin --password=admin --no-interaction -w
          bin/console galette:plugins:install-db --all
        if: startsWith(matrix.db-image, 'postgres')

      - name: Init for MariaDB
        run: |
          cd galette-core
          mysql -e 'create database IF NOT EXISTS galette_tests;' -u galette_tests --password=g@l3tte -h 127.0.0.1 -P 3306
          bin/console galette:install -v --dbtype=mysql --dbhost=127.0.0.1 --dbname=galette_tests --dbuser=galette_tests --dbpass=g@l3tte --admin=admin --password=admin --no-interaction -w
          bin/console galette:plugins:install-db --all
        if: startsWith(matrix.db-image, 'mysql') || startsWith(matrix.db-image, 'mariadb')

      - name: Unit tests
        run: |
          cd galette-core/galette/plugins/plugin-paypal
          ../../vendor/bin/phpunit --test-suffix=.php --bootstrap tests/TestsBootstrap.php --no-coverage --process-isolation tests/GalettePaypal/
